modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/laffs1/minecraft-mods/issues"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "chimericdream"
description = '''
${mod_description}
'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[26.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_compat},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_compat},)"
ordering = "AFTER"
side = "BOTH"
